config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :check do
    post :check, on: :collection, defaults: { format: :json }
  end

  concern :toggle do
    post :toggle, on: :member, defaults: { format: :json }
  end

  concern :priority do
    post :priority, on: :member, defaults: { format: :json }
  end

  get 'sitemap' => 'index#sitemap', defaults: { format: :xml }

  resources :albums, :photos, :photo_tags, :stories, only: %i[update destroy]

  scope '(:locale)', constraints: { locale: /ru|en/ } do
    root 'index#index'

    resources :albums, :photos, :photo_tags, except: %i[update destroy show], concerns: :check
    get 'albums/:id-:slug' => 'albums#show', as: :show_album
    get 'stream' => 'photos#stream'

    namespace :admin do
      resources :albums, only: %i[index show]
      resources :photos, only: %i[index show], concerns: %i[toggle priority] do
        member do
          put 'tags/:tag_id' => :add_tag, as: :tag
          delete 'tags/:tag_id' => :remove_tag
        end
      end
      resources :photo_tags, only: %i[index show]
      resources :featured_photos, :featured_albums, only: %i[index create destroy], concerns: %i[priority toggle]
    end
  end
end

app/models/album.rb
# frozen_string_literal: true

# Album
#
# Attributes:
#   created_at [DateTime]
#   date [Date], optional
#   description [string], optional
#   image [SimpleImageUploader], optional
#   image_alt_text [string], optional
#   name [string]
#   photos_count [integer]
#   slug [string]
#   updated_at [DateTime]
class Album < ApplicationRecord
  include Checkable
  include HasUuid
  include RequiredUniqueName
  include RequiredUniqueSlug

  DESCRIPTION_LIMIT = 255
  META_LIMIT = 255
  NAME_LIMIT = 75
  SLUG_LIMIT = 75
  SLUG_PATTERN = /\A[a-z0-9][-_a-z0-9]*[a-z0-9]\z/i.freeze
  SLUG_PATTERN_HTML = '^[a-zA-Z0-9][-_a-zA-Z0-9]*[a-zA-Z0-9]$'

  mount_uploader :image, PhotoUploader

  has_many :photos, dependent: :destroy
  has_many :featured_albums, dependent: :delete_all

  before_validation :normalize_slug
  validates_presence_of :image
  validates_length_of :description, maximum: DESCRIPTION_LIMIT
  validates_length_of :image_alt_text, maximum: META_LIMIT
  validates_length_of :name, maximum: NAME_LIMIT
  validates_length_of :slug, maximum: SLUG_LIMIT
  validates_format_of :slug, with: SLUG_PATTERN

  scope :recent, -> { order(updated_at: :desc) }
  scope :themed, -> { where(date: nil) }
  scope :stories, -> { where('date is not null').order(date: :desc) }
  scope :list_for_visitors, -> { recent }
  scope :list_for_administration, -> { recent }

  def self.entity_parameters
    %i[date description image image_alt_text name slug]
  end

  def url
    "/albums/#{id}-#{slug}"
  end

  def text_for_link
    date.nil? ? name : "#{name} (#{date})"
  end

  private

  def normalize_slug
    self.slug = Canonizer.transliterate(name) if slug.blank?
    self.slug = slug.to_s.downcase[0..SLUG_LIMIT]
  end
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

# Managing albums
class AlbumsController < ApplicationController
  before_action :restrict_access, except: %i[index show]
  before_action :set_entity, only: %i[edit update destroy show]

  layout 'admin', except: %i[index show]

  # post /albums/check
  def check
    @entity = Album.instance_for_check(params[:entity_id], entity_parameters)

    render 'shared/forms/check'
  end

  # get /albums
  def index
    @collection = {
      themed: Album.themed.list_for_visitors,
      stories: Album.stories
    }
  end

  # get /albums/new
  def new
    @entity = Album.new
  end

  # post /albums
  def create
    @entity = Album.new(entity_parameters)
    if @entity.save
      form_processed_ok(admin_album_path(id: @entity.id))
    else
      form_processed_with_error(:new)
    end
  end

  # get /albums/:id-:slug
  def show
    @entity = Album.includes(:photos).find_by(id: params[:id])
    handle_http_404('Cannot find album') if @entity.nil?
  end

  # get /albums/:id/edit
  def edit
  end

  # patch /albums/:id
  def update
    if @entity.update(entity_parameters)
      form_processed_ok(admin_album_path(id: @entity.id))
    else
      form_processed_with_error(:edit)
    end
  end

  # delete /albums/:id
  def destroy
    flash[:notice] = t('albums.destroy.success') if @entity.destroy

    redirect_to(admin_albums_path)
  end

  protected

  def component_class
    Biovision::Components::PhotosComponent
  end

  def restrict_access
    error = 'Managing albums is not allowed'
    handle_http_401(error) unless component_handler.allow?
  end

  def set_entity
    @entity = Album.find_by(id: params[:id])
    handle_http_404('Cannot find album') if @entity.nil?
  end

  def entity_parameters
    params.require(:album).permit(Album.entity_parameters)
  end
end

app/views/admin/albums/index.html.erb
<% content_for :meta_title, t('.title') %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <span><%= t('admin.albums.nav_item.text') %></span>
<% end %>

<article>
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_path) %></li>
    <li><%= world_icon(albums_path) %></li>
    <li><%= create_icon(new_album_path) %></li>
  </ul>

  <%=
    render(
        partial: 'shared/admin/list',
        locals: {
            collection: @collection
        }
    )
  %>
</article>

app/views/admin/albums/show.html.erb
<% content_for :meta_title, t('.title', name: @entity.name) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.albums.nav_item.text'), admin_albums_path) %>
  <span><%= @entity.slug %></span>
<% end %>

<article>
  <h1><%= @entity.name %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_albums_path) %></li>
    <li><%= world_icon(show_album_path(id: @entity.id, slug: @entity.slug)) %></li>
    <li><%= edit_icon(edit_album_path(id: @entity.id)) %></li>
  </ul>

  <dl>
    <%= render partial: 'shared/entity/image', locals: { entity: @entity } %>

    <div>
      <dt><%= t('activerecord.attributes.album.name') %></dt>
      <dd><%= @entity.name %></dd>
    </div>

    <div>
      <dt><%= t('attributes.slug') %></dt>
      <dd><%= @entity.slug %></dd>
    </div>

    <%= render partial: 'components/photos/entity/description', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/uuid', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/timestamps', locals: { entity: @entity } %>
  </dl>

  <%=
    render(
        partial: 'admin/albums/entity/photos',
        locals: {
            entity: @entity,
            collection: @entity.photos.list_for_administration
        }
    )
  %>

  <%=
    render(
        partial: 'admin/albums/entity/new_photo',
        locals: {
            entity: @entity
        }
    )
  %>
</article>